"""init

Revision ID: 28e415945385
Revises: 
Create Date: 2026-04-23 23:37:14.573770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e415945385'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Идентификатор цитаты',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Текст цитаты',
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['id'])
        batch_op.create_table_comment(
        'Таблица цитат',
        existing_comment='Таблица с цитатами'
    )
        batch_op.drop_column('author')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True, comment='Рейтинг (1-5 звезд)'))
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Автор цитаты'))
        batch_op.create_table_comment(
        'Таблица с цитатами',
        existing_comment='Таблица цитат'
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=255),
               comment='Текст цитаты',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='Идентификатор цитаты',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
