"""task 3.2

Revision ID: c9c14eccf2c0
Revises: 28e415945385
Create Date: 2026-04-23 23:57:13.469019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c14eccf2c0'
down_revision = '28e415945385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True))
        batch_op.drop_table_comment(
        existing_comment='Таблица авторов'
    )

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_table_comment(
        existing_comment='Таблица цитат'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Таблица цитат',
        existing_comment=None
    )
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('rating')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Таблица авторов',
        existing_comment=None
    )
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
